version: '3.4'

services:
  myexpressapp:
    image: myexpressapp
    build:
      context: L06-02 Using VS Code
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
